### ISSUE TITLE
Assorted bugs

### ISSUE THREAD

**Issue by telmob** [givanz/Vvveb#175]
When saving cookie-notice page, i get the error '/plugins/cookie-notice/notice.html is not writable'. But it is. Pop-up also doesn't show.
Can't change an image. (I can in vvvebjs editor)
Can't send e-mail. I get error 500.
If i clear the error log, it doesn't populate anymore.

My error log:

storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(/home/storage/4/aa/20/site/public_html/install/../index.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(): Failed opening '/home/storage/4/aa/20/site/public_html/install/../index.php' for inclusion (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Warning:  require_once(/home/storage/4/aa/20/site/public_html/system/core/startup.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Failed opening required '/home/storage/4/aa/20/site/public_html/system/core/startup.php' (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/index.php:76
Stack trace:
#0 /home/storage/4/aa/20/site/public_html/install/index.php(51): include()
#1 {main}
  thrown in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(/home/storage/4/aa/20/site/public_html/install/../index.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(): Failed opening '/home/storage/4/aa/20/site/public_html/install/../index.php' for inclusion (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Warning:  require_once(/home/storage/4/aa/20/site/public_html/system/core/startup.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Failed opening required '/home/storage/4/aa/20/site/public_html/system/core/startup.php' (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/index.php:76
Stack trace:
#0 /home/storage/4/aa/20/site/public_html/install/index.php(51): include()
#1 {main}
  thrown in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(/home/storage/4/aa/20/site/public_html/install/../index.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(): Failed opening '/home/storage/4/aa/20/site/public_html/install/../index.php' for inclusion (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Warning:  require_once(/home/storage/4/aa/20/site/public_html/system/core/startup.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Failed opening required '/home/storage/4/aa/20/site/public_html/system/core/startup.php' (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/index.php:76
Stack trace:
#0 /home/storage/4/aa/20/site/public_html/install/index.php(51): include()
#1 {main}
  thrown in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(/home/storage/4/aa/20/site/public_html/install/../index.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(): Failed opening '/home/storage/4/aa/20/site/public_html/install/../index.php' for inclusion (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Warning:  require_once(/home/storage/4/aa/20/site/public_html/system/core/startup.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Failed opening required '/home/storage/4/aa/20/site/public_html/system/core/startup.php' (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/index.php:76
Stack trace:
#0 /home/storage/4/aa/20/site/public_html/install/index.php(51): include()
#1 {main}
  thrown in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(/home/storage/4/aa/20/site/public_html/install/../index.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:37:05 America/Sao_Paulo] PHP Warning:  include(): Failed opening '/home/storage/4/aa/20/site/public_html/install/../index.php' for inclusion (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/install/index.php on line 51
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Warning:  require_once(/home/storage/4/aa/20/site/public_html/system/core/startup.php): Failed to open stream: No such file or directory in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 15:42:50 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Failed opening required '/home/storage/4/aa/20/site/public_html/system/core/startup.php' (include_path='.:/opt/remi/php83/root/usr/share/pear:/opt/remi/php83/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/storage/4/aa/20/site/public_html/index.php:76
Stack trace:
#0 /home/storage/4/aa/20/site/public_html/install/index.php(51): include()
#1 {main}
  thrown in /home/storage/4/aa/20/site/public_html/index.php on line 76
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:15 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_index.html-edit on line 96
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  Undefined array key "url" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit on line 88
[02-Aug-2024 16:16:38 America/Sao_Paulo] PHP Warning:  http_response_code(): Cannot set response code - headers already sent (output started at /home/storage/4/aa/20/site/public_html/storage/compiled-templates/app_1_landing_error404.html-edit:125) in /home/storage/4/aa/20/site/public_html/system/core/frontcontroller.php on line 113
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 598
[02-Aug-2024 16:18:23 America/Sao_Paulo] PHP Warning:  Undefined array key "status" in /home/storage/4/aa/20/site/public_html/storage/compiled-templates/admin_1_default_localization_currency.html on line 599

**Comment by givanz** [comment]
Thanks for the bug reports, saving cookie notice page and php notices are fixed in the last update https://github.com/givanz/Vvveb/commit/f6fc936cae928527ee7509f5e4d77c99f6838f4d a

You can redownload `latest.zip` and update the files on your server.

The 500 error shows when sending a test email from email settings page? https://demo.vvveb.com/admin/index.php?module=settings/email

The error log file shown in https://demo.vvveb.com/admin/index.php?module=tools/errorlog is set to `storage/logs/error_log`? 

If it's set to `storage/logs/error_log` then this is a fallback mode that might or might not work and is used if the php error log is not set, you can try to set a value for php error_log in php.ini.

You can also try to set write permissions for the error log file maybe php does not have write access to the file.

Can you please check if the error message is shown in developer tools (F12 key) network tab?

![error500](https://github.com/user-attachments/assets/21e37977-0ed0-479f-9b20-535a7aecb87c)

**Comment by telmob** [comment]
> Thanks for the bug reports, saving cookie notice page and php notices are fixed in the last update [f6fc936](https://github.com/givanz/Vvveb/commit/f6fc936cae928527ee7509f5e4d77c99f6838f4d) a

Thank you! However, i can't seem to change the cookie notice text translation. Can you tell me if there's a specific field for it?

> You can redownload `latest.zip` and update the files on your server.

Already done and testing.

> The 500 error shows when sending a test email from email settings page? https://demo.vvveb.com/admin/index.php?module=settings/email

It's now asking for username and password. What is it?!
I'm testing everything, and i'll let you know as soon as i have more conclusions.

**Comment by givanz** [comment]
> Undefined index: description, Undefined index: contact-email

Please check that you have set site description and contact email for the selected site language in `admin > settings > site > description > site title`.

https://demo.vvveb.com/admin/index.php?module=settings/site&site_id=1

For error log, you can try to create the `/var/log/php-fpm/pro1031/php-8.3_error.log` file and set write permissions.

I think that mail function is disabled in your php configuration, you can try to use the SMTP option with a free provider like brevo, gmail, mailgun etc.
