### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by annearndt** [givanz/Vvveb#5]
After installation I'm receiving this error:

Fatal error: Uncaught Exception: Unknown column 'np_value' in 'field list' INSERT INTO `np_option` (`key`, `value`, `site_id`) VALUES ( "site-title", "XXXXXX", 1 ) ON DUPLICATE KEY UPDATE `np_value` = values(`value`) - INSERT INTO `np_option` (`key`, `value`, `site_id`) VALUES ( :key, :value, :site_id ) ON DUPLICATE KEY UPDATE `np_value` = values(`value`) in /home/host/domains/xxxxxxx/public_html/vvveb/system/db/mysqli.php:336 Stack trace: #0 /home/host/domains/xxxxxxx/public_html/vvveb/storage/model/install/optionsql.php(106): Vvveb\System\Db\Mysqli->execute() #1 /home/host/domains/xxxxxxx/public_html/vvveb/system/option.php(67): Vvveb\Sql\OptionSQL->setOption() #2 /home/host/domains/xxxxxxx/public_html/vvveb/system/functions/functions.php(96): Vvveb\System\Option->multiSet() #3 /home/host/domains/xxxxxxx. in /home/host/domains/xxxxxxx/public_html/vvveb/system/db/mysqli.php on line 336

Any idea about how I can solve that?

**Comment by givanz** [comment]
Hi

Thanks for testing Vvveb, this error was caused by a bug from table prefix option, please redownload the zip file to get the fixed version.
