### ISSUE TITLE
Page editor not loading, Cannot read properties of undefined (reading 'menu')

### ISSUE THREAD

**Issue by CipherBytesOfDust** [givanz/Vvveb#69]
Hi, getting the following error when opening the page editor..

Uncaught TypeError: Cannot read properties of undefined (reading 'menu')
    at new MenuComponent (menu.js:66:26)
    at menu.js:91:21
    
The loading spinner remains and the page to edit does not load.

Thanks

**Comment by givanz** [comment]
Hi

It looks like Vvveb.data is null but I'm unable to make it null even if I delete all menus, can you please paste the line that begins with `Vvveb.data` from the page view source (CTRL + U).

Can you also check php error log from tools > system info > error log if there are any errors?

**Comment by CipherBytesOfDust** [comment]
The path I'm on is - /admin/?module=editor/editor&url=/&template=index.html
but vvveb.data is not found in the source
[source.txt](https://github.com/givanz/Vvveb/files/13961982/source.txt)

PHP error log is empty :s

**Comment by givanz** [comment]
Thanks for the source file, I was able to track down the issue to some unclosed script tags that on some php configurations it seems that it causes the script tag to be removed.

The fix is available for download in the latest.zip, you will need to update at least `public/admin` and `system` folders and clear cache.

**Comment by CipherBytesOfDust** [comment]
I have not had time to review this yet but thanks for the quick replies and potential solution, will let you know how I get on. 👍🏼

**Comment by CipherBytesOfDust** [comment]
> Thanks for the source file, I was able to track down the issue to some unclosed script tags that on some php configurations it seems that it causes the script tag to be removed.
> 
> The fix is available for download in the latest.zip, you will need to update at least `public/admin` and `system` folders and clear cache.

Updated files, cleared cache but the issue persists
