### ISSUE TITLE
What's the PHP version?

### ISSUE THREAD

**Issue by ninoppp** [givanz/Vvveb#9]
I just spunt Vvvweb up on a VPS behind a simple apache config and got this error

```
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/vvveb/system/functions.php on line 204

Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /var/www/vvveb/system/functions.php on line 204

Fatal error: Uncaught Error: Class "DomDocument" not found in /var/www/vvveb/system/psttt.php:180 Stack trace: #0 /var/www/vvveb/system/core/view.php(102): Psttt->__construct() #1 /var/www/vvveb/system/core/frontcontroller.php(127): Vvveb\System\Core\View::getInstance() #2 /var/www/vvveb/system/core/frontcontroller.php(170): Vvveb\System\Core\FrontController::di() #3 /var/www/vvveb/system/core/frontcontroller.php(253): Vvveb\System\Core\FrontController::call() #4 /var/www/vvveb/system/core/frontcontroller.php(305): Vvveb\System\Core\FrontController::redirect() #5 /var/www/vvveb/system/core/startup.php(321): Vvveb\System\Core\FrontController::dispatch() #6 /var/www/vvveb/index.php(122): Vvveb\System\Core\start() #7 /var/www/vvveb/install/index.php(36): include('...') #8 {main} thrown in /var/www/vvveb/system/psttt.php on line 180
```
Looks l'm using a wrong php version (I'm using 8.1). Which one am I supposed to use?

**Comment by givanz** [comment]
It works with both 7.x  and 8.x but it was developed mostly on 7.4 and is currently safer to use this version.
The fatal error is caused by missing libxml php extension, the installer checks missing requirements later in code, I will add some earlier checks to avoid this error.

**Comment by ninoppp** [comment]
Alright, thanks :) In case you've got a list with the requirements, maybe adding them to the installation docs would be nice
