### ISSUE TITLE
Error Editing Main Footer Link name on PGSQL

### ISSUE THREAD

**Issue by jeromeatneotek** [givanz/Vvveb#91]
DUPLICATE KEY ERROR
#0 C:\Domains\myweb\wwwroot\system\db\pgsql.php(291): pg_result_error()
#1 C:\Domains\myweb\wwwroot\storage\model\admin\menusql.pgsql.php(1200): Vvveb\System\Db\Pgsql-&gt;execute()
#2 C:\Domains\myweb\wwwroot\admin\controller\content\menus.php(122): Vvveb\Sql\MenuSQL-&gt;editMenuItem()
#3 [internal function]: Vvveb\Controller\Content\Menus-&gt;add()
#4 C:\Domains\myweb\wwwroot\system\core\frontcontroller.php(229): call_user_func()
#5 C:\Domains\myweb\wwwroot\system\core\frontcontroller.php(298): Vvveb\System\Core\FrontController::call()
#6 C:\Domains\myweb\wwwroot\system\core\frontcontroller.php(364): Vvveb\System\Core\FrontController::redirect()
#7 C:\Domains\myweb\wwwroot\system\core\startup.php(355): Vvveb\System\Core\FrontController::dispatch()
#8 C:\Domains\myweb\wwwroot\index.php(138): Vvveb\System\Core\start()
#9 C:\Domains\myweb\wwwroot\admin\index.php(41): include('...')
#10 C:\Domains\myweb\wwwroot\public\admin\index.php(26): include('...')
#11 {main}

**Comment by givanz** [comment]
This issues is the same as https://github.com/givanz/Vvveb/issues/89 and is fixed the same with sequence restart or reinstall.
